### ISSUE TITLE
Error when using

### ISSUE THREAD

**Issue by jacwright** [michelsalib/chai-shallow-deep-equal#15]
I get this error when using shallow deep equal. I assume it needs to be updated for the latest chai API.
```
TypeError: msg.replace is not a function
      at Object.module.exports [as getMessage] (node_modules/chai/lib/chai/utils/getMessage.js:45:6)
      at Assertion.assert (node_modules/chai/lib/chai/assertion.js:105:22)
      at Assertion.<anonymous> (node_modules/chai-shallow-deep-equal/chai-shallow-deep-equal.js:93:18)
      at Assertion.ctx.(anonymous function) [as shallowDeepEqual] (node_modules/chai/lib/chai/utils/addMethod.js:40:25)
      at Context.<anonymous> (test/observer-chain.js:33:28)
```

**Comment by tomatau** [comment]
same

**Comment by JavaTheNutt** [comment]
Is there a fix for this yet? I'm having the same issue.

**Comment by bcfisher** [comment]
me too.

**Comment by ShayanAhmad** [comment]
Still no luck, anyone?

**Comment by drigberg** [comment]
Still no luck

**Comment by papandreou** [comment]
Seems to happen when the subject is `undefined` and it's being compared to an object that it doesn't satisfy. Repro:

```js
const chai = require('chai');
chai.use(require('chai-shallow-deep-equal'));
const expect = require('chai').expect;
expect(undefined).to.shallowDeepEqual({
  foo: 123
});
```

```
/path/to/project/node_modules/chai/lib/chai/utils/getMessage.js:46
    .replace(/#\{this\}/g, function () { return objDisplay(val); })
     ^

TypeError: msg.replace is not a function
    at Object.getMessage (/path/to/project/node_modules/chai/lib/chai/utils/getMessage.js:46:6)
    at Proxy.Assertion.assert (/path/to/project/node_modules/chai/lib/chai/assertion.js:139:18)
    at Proxy.<anonymous> (/path/to/project/node_modules/chai-shallow-deep-equal/chai-shallow-deep-equal.js:93:18)
    at Proxy.methodWrapper (/path/to/project/node_modules/chai/lib/chai/utils/addMethod.js:57:25)
    at Object.<anonymous> (/path/to/project/shallowDeep.js:4:22)
    at Module._compile (module.js:660:30)
    at Object.Module._extensions..js (module.js:671:10)
    at Module.load (module.js:573:32)
    at tryModuleLoad (module.js:513:12)
    at Function.Module._load (module.js:505:3)
```

**Comment by Cactusbone** [comment]
https://github.com/alexjeffburke/chai-better-shallow-deep-equal handles undefined properly
